# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798

name: githubactions_demo

on:
  push:
    branches:
      - master
      - develop
      - 'release/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Build with dotnet
      run: dotnet build ContosoCrafts.Website/ContosoCrafts.Website.csproj --configuration Release

    - name: dotnet publish
      run: dotnet publish ContosoCrafts.Website/ContosoCrafts.Website.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:        
        name: artifact        
        path: ${{env.DOTNET_ROOT}}/myapp         
        if-no-files-found: warn        
        retention-days: 30
  
  deploy-to-dev:
      needs: build
      name: Deploy to dev
      runs-on: windows-latest
      environment:
        name: dev
        url: http://dev.my-app.com
      steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:          
          name: artifact
          path: ${{env.DOTNET_ROOT}}/myapp
      
      - name: Deploy
        run: |
          ping 35.244.42.144
          echo "check the results of ping... "
          net use "${{secrets.HOSTPATH}}" /user:"${{secrets.USER}}" "${{secrets.PASSWORD}}"
          robocopy ${{env.DOTNET_ROOT}}/myapp/obj/Release/myapp "${{secrets.HOSTPATH}}" /s /e


  deploy-to-uat:
    needs: build
    name: Deploy to uat
    environment:
      name: uat
      url: http://uat.myapp.com
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo Deploying to UAT environment
    

